print("Aderemi's APRIL PLANNER")
print("What's your April goal?", end=' ')
goal = input()
print("Where do you see yourself in the next few months?", end=' ')
months = input()
print("Do you have friends?", end=' ')
friends = input()
age = input("How are you? ")
goal = input("What's your April goal? ")
friends = input("Do you have friends? ")
